vich_uploader:
    db_driver: orm
    mappings:
        posters_directory:
            uri_prefix: '%app.path.posters_directory%'
            upload_destination: '%kernel.project_dir%/public%app.path.posters_directory%'
        books_directory:
            uri_prefix: '%app.path.books_directory%'
            upload_destination: '%kernel.project_dir%/public%app.path.books_directory%'